In [53]:
#Correlación Pearson con pandas.
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('C:\\Users\\Intel\\Documents\\Mis documentos IDEA\\Samples\\Exportaciones.ILB\\Tabladinámica10.xlsx')
df.head()
del df['NUM_FACT']
df.head()
df.corr(method='pearson')

#plt.plot(df['COD_PROD_06'], df['TOTAL'], "ro")
#plt.xlabel('Producto 06')
#plt.ylabel('Ventas')

COD_PROD_01  COD_PROD_02  COD_PROD_03  COD_PROD_04  COD_PROD_05  \
COD_PROD_01     1.000000    -0.002795    -0.007691    -0.003901    -0.017263   
COD_PROD_02    -0.002795     1.000000    -0.009383    -0.004759    -0.021062   
COD_PROD_03    -0.007691    -0.009383     1.000000    -0.013097    -0.057958   
COD_PROD_04    -0.003901    -0.004759    -0.013097     1.000000    -0.029398   
COD_PROD_05    -0.017263    -0.021062    -0.057958    -0.029398     1.000000   
COD_PROD_06    -0.002304    -0.002811    -0.007735    -0.003923    -0.017361   
TOTAL           0.000831    -0.003440    -0.007493     0.055012     0.032142   

             COD_PROD_06     TOTAL  
COD_PROD_01    -0.002304  0.000831  
COD_PROD_02    -0.002811 -0.003440  
COD_PROD_03    -0.007735 -0.007493  
COD_PROD_04    -0.003923  0.055012  
COD_PROD_05    -0.017361  0.032142  
COD_PROD_06     1.000000  0.996930  
TOTAL           0.996930  1.000000

In [54]:
#Correlación Pearson con numpy
import numpy as np

CORR6 = np.corrcoef(df['COD_PROD_06'],df['TOTAL'])
CORR5 = np.corrcoef(df['COD_PROD_05'],df['TOTAL'])
CORR4 = np.corrcoef(df['COD_PROD_04'],df['TOTAL'])
CORR3 = np.corrcoef(df['COD_PROD_03'],df['TOTAL'])
CORR2 = np.corrcoef(df['COD_PROD_02'],df['TOTAL'])
CORR1 = np.corrcoef(df['COD_PROD_01'],df['TOTAL'])

print(CORR6)
print(CORR5)
print(CORR4)
print(CORR3)
print(CORR2)
print(CORR1)

[[1.         0.99693027]
 [0.99693027 1.        ]]
[[1.         0.03214211]
 [0.03214211 1.        ]]
[[1.         0.05501175]
 [0.05501175 1.        ]]
[[ 1.        -0.0074928]
 [-0.0074928  1.       ]]
[[ 1.         -0.00344006]
 [-0.00344006  1.        ]]
[[1.00000000e+00 8.30539999e-04]
 [8.30539999e-04 1.00000000e+00]]


In [55]:
#Correlación Pearson con scipy
from scipy import stats

c6 = stats.pearsonr(df['COD_PROD_06'],df['TOTAL'])
c5 = stats.pearsonr(df['COD_PROD_05'],df['TOTAL'])
c4 = stats.pearsonr(df['COD_PROD_04'],df['TOTAL'])
c3 = stats.pearsonr(df['COD_PROD_03'],df['TOTAL'])
c2 = stats.pearsonr(df['COD_PROD_02'],df['TOTAL'])
c1 = stats.pearsonr(df['COD_PROD_01'],df['TOTAL'])
print(c6)
print(c5)
print(c4)
print(c3)
print(c2)
print(c1)


(0.996930270131928, 0.0)
(0.032142112200437334, 0.3370817866001227)
(0.05501175102730851, 0.10022047614296177)
(-0.007492802890192813, 0.822972656588921)
(-0.00344005940841924, 0.9181902823917176)
(0.000830539999422464, 0.9802158731696501)


In [56]:
#Correlación Spearman con pandas
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('C:\\Users\\Intel\\Documents\\Mis documentos IDEA\\Samples\\Exportaciones.ILB\\Tabladinámica10.xlsx')
df.head()
del df['NUM_FACT']
df.head()
df.corr(method='spearman')

COD_PROD_01  COD_PROD_02  COD_PROD_03  COD_PROD_04  COD_PROD_05  \
COD_PROD_01     1.000000    -0.003890    -0.012222    -0.007833    -0.092657   
COD_PROD_02    -0.003890     1.000000    -0.014121    -0.009049    -0.107051   
COD_PROD_03    -0.012222    -0.014121     1.000000    -0.028432    -0.336336   
COD_PROD_04    -0.007833    -0.009049    -0.028432     1.000000    -0.215548   
COD_PROD_05    -0.092657    -0.107051    -0.336336    -0.215548     1.000000   
COD_PROD_06    -0.003367    -0.003890    -0.012222    -0.007833    -0.092657   
TOTAL           0.077556     0.007838     0.083242     0.199820     0.762715   

             COD_PROD_06     TOTAL  
COD_PROD_01    -0.003367  0.077556  
COD_PROD_02    -0.003890  0.007838  
COD_PROD_03    -0.012222  0.083242  
COD_PROD_04    -0.007833  0.199820  
COD_PROD_05    -0.092657  0.762715  
COD_PROD_06     1.000000  0.100094  
TOTAL           0.100094  1.000000

In [57]:
#Correlación Spearman con scipy
from scipy import stats

C6 = stats.spearmanr(df['COD_PROD_06'],df['TOTAL'])
C5 = stats.spearmanr(df['COD_PROD_05'],df['TOTAL'])
C4 = stats.spearmanr(df['COD_PROD_04'],df['TOTAL'])
C3 = stats.spearmanr(df['COD_PROD_03'],df['TOTAL'])
C2 = stats.spearmanr(df['COD_PROD_02'],df['TOTAL'])
C1 = stats.spearmanr(df['COD_PROD_01'],df['TOTAL'])
print(C6)
print(C5)
print(C4)
print(C3)
print(C2)
print(C1)

SpearmanrResult(correlation=0.10009409823426017, pvalue=0.002734237934284886)
SpearmanrResult(correlation=0.7627145125422655, pvalue=5.152684052961035e-171)
SpearmanrResult(correlation=0.1998197051934975, pvalue=1.6692693298847711e-09)
SpearmanrResult(correlation=0.08324199826137126, pvalue=0.012782875777367107)
SpearmanrResult(correlation=0.007837615227853811, pvalue=0.8149701455508731)
SpearmanrResult(correlation=0.07755642532633315, pvalue=0.020385623258571062)


In [58]:
#Correlación Kendall con scipy
import scipy.stats
from scipy import stats

C6 = scipy.stats.kendalltau(df['COD_PROD_06'],df['TOTAL'])
C5 = scipy.stats.kendalltau(df['COD_PROD_05'],df['TOTAL'])
C4 = scipy.stats.kendalltau(df['COD_PROD_04'],df['TOTAL'])
C3 = scipy.stats.kendalltau(df['COD_PROD_03'],df['TOTAL'])
C2 = scipy.stats.kendalltau(df['COD_PROD_02'],df['TOTAL'])
C1 = scipy.stats.kendalltau(df['COD_PROD_01'],df['TOTAL'])

print(C6)
print(C5)
print(C4)
print(C3)
print(C2)
print(C1)

KendalltauResult(correlation=0.08195162614371349, pvalue=0.0027492645317029776)
KendalltauResult(correlation=0.8028435716684932, pvalue=1.57185287952293e-279)
KendalltauResult(correlation=0.16412175697057554, pvalue=1.7576235038473602e-09)
KendalltauResult(correlation=0.07063439714722591, pvalue=0.009156887797044266)
KendalltauResult(correlation=0.006477961821423651, pvalue=0.8128374588931795)
KendalltauResult(correlation=0.06350178360874134, pvalue=0.02032365124093628)


In [9]:
#Set de pruebas Correlación Spearman con pandas y scipy
import pandas as pd

df = pd.read_excel('C:\\Users\\Intel\\Documents\\Mis documentos IDEA\\Samples\\Archivos fuente.ILB\\Spearman.xlsx')
df.corr(method='spearman')

CI        TV
CI  1.000000 -0.213632
TV -0.213632  1.000000

In [7]:
#Correlación Spearman con scipy
from scipy import stats

C6 = stats.spearmanr(df['CI'],df['TV'])
print(C6)

SpearmanrResult(correlation=-0.21363150574154266, pvalue=0.5534311070541142)
